### ISSUE TITLE
textDocument/signatureHelp response is invalid

### ISSUE THREAD

**Issue by veksha** [zobo/php-language-server#18]
I send `textDocument/signatureHelp`
and get an invalid response from server: `{'signatures': null, 'activeSignature': null, 'activeParameter': null}`

according to [LSP specs](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelp) ` If no signatures are available the signature help request should return "null".`

`null` values are not valid for members of SignatureHelp interface.

```typescript
export interface SignatureHelp {
	/**
	 * One or more signatures. If no signatures are available the signature help
	 * request should return `null`.
	 */
	signatures: SignatureInformation[];
        activeSignature?: uinteger;
        activeParameter?: uinteger;
```

**Comment by zobo** [comment]
Doesn't seem to make much difference in VsCode, but I can change this. Thanks.

**Comment by veksha** [comment]
I'm using it in CudaText. it complains in status bar:
![image](https://user-images.githubusercontent.com/275333/174006073-148afb7f-3dc4-4600-95eb-50fe70481047.png)
This is not a crash, but still it is better to stick to the specification.

Thanks!

BTW: I'm planing to open an issue about this server not working in stdio mode. only working with through TCP socket. Do you confirm it is not working for you too?

**Comment by veksha** [comment]
okay thank you.
