### ISSUE TITLE
PHP problems reported if there is class method of same name as built-in PHP function

### ISSUE THREAD

**Issue by kkozlik** [zobo/php-language-server#22]
Look at the attached picture. There is a class method `match` that generate 11 problem reported by VS code although this is fine for PHP. When the function is renamed those problems disappear.

![obrazek](https://user-images.githubusercontent.com/1277199/174311287-81aea3a8-b024-4350-bc99-e9b7c190dd73.png)

**Comment by zobo** [comment]
Match isn't properly categorized as a keyword. Will submit a fix to parser.

**Comment by zobo** [comment]
Was released with version 1.0.11.
https://github.com/zobo/vscode-php-intellisense/commit/c242c015b80f3af2a00a6c2c2041f831e4187eda
