### ISSUE TITLE
Is it possible to ignore specific folders?

### ISSUE THREAD

**Issue by PF4Public** [zobo/php-language-server#25]
While indexing it scans the whole project. Would it be possible to exclude some folders from the scan? Which allows sparing some memory (and I/O) on unneeded indexes.

**Comment by zobo** [comment]
Yes, this is planned. There is a bunch of related issues in the original repository, for example: https://github.com/felixfbecker/php-language-server/issues/159

A bit of an problem is that the Language Server Protocol does not support this concept natively and needs to be implemented as an extension to either the protocol or the configuration...

**Comment by zobo** [comment]
Added support in #45 and https://github.com/zobo/vscode-php-intellisense/pull/60 released as 1.1.0 . Setting is `php.files.exclude`.

**Comment by zobo** [comment]
Can you give some example of what you are trying? I have one here: https://github.com/zobo/vscode-php-intellisense#features
