### ISSUE TITLE
rand() not recognized

### ISSUE THREAD

**Issue by Fabix84** [zobo/php-language-server#43]
Hi,

php function rand() is not recognized.
![random](https://user-images.githubusercontent.com/41300554/210386003-5c411d32-f165-4c30-9461-dda9584d4eb7.png)

**Comment by zobo** [comment]
Hum, tried and it works here. Do other functions work? Something you defined in the file?

**Comment by zobo** [comment]
No feedback. Try also  `\rand(1,900);`
