### ISSUE TITLE
Git dirrectory syntax error warnings

### ISSUE THREAD

**Issue by TuzelKO** [zobo/php-language-server#6]
![изображение](https://user-images.githubusercontent.com/38176435/146360001-0b9b55c1-bfbb-47ba-8fe4-9efd005973a4.png)

Files are scanned in the .git directory. This results in false positives of syntax error warnings.

Code-OSS

Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-07T19:37:13.664Z
Electron: 13.6.3
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.83-1-MANJARO

**Comment by TuzelKO** [comment]
Is there any way to exclude project directories from the list of analyzed ones?

If yes, then you need to add this functionality to the extension for VS Code

**Comment by TuzelKO** [comment]
And I wanted to say thank you for taking this project and the extension for it to support. The alternative with proprietary intelliphence was a little troublesome.

**Comment by zobo** [comment]
Hi!
Sorry for the late reply. Notifications were off...
Interesting, I have not yet seen such an Issue. Will have a look

**Comment by zobo** [comment]
Note for me https://github.com/felixfbecker/php-language-server/issues/159

**Comment by zobo** [comment]
Implemented in https://github.com/zobo/vscode-php-intellisense/pull/60

Add this to settings.json 

`"php.files.exclude": [ "generated/**/*" ]`
