### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GauravPunani** [zobo/php-language-server#8]
- Issue Type: `Performance`
- Extension Name: `php-intellisense`
- Extension Version: `1.0.4`
- OS Version: `Linux x64 5.13.0-28-generic`
- VS Code version: `1.63.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/zobo.php-intellisense-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by zobo** [comment]
Hi. There is sadly no attachment. Please attach the file so I can debug the issue. Another option would be to attach the language server logs.
Open settings, and filter for `php-intellisense.trace.server`. Set to verbose. Restart VS Code and let it run for a while.
Then open pannel, OUTPUT and select `PHP Language Server`. Do `Copy` and attach the log file.
It might be very large...

**Comment by raydleemsc** [comment]
[zobo.php-intellisense-unresponsive.cpuprofile.txt](https://github.com/zobo/php-language-server/files/9476235/zobo.php-intellisense-unresponsive.cpuprofile.txt)

**Comment by zobo** [comment]
No extra info. Closing. The extension does need quite some CPU processing when it re-indexes everything. Working on changes how things are caches and stored to avoid unneeded re-indexing.
